### PR TITLE
Containerizing ANTs and ants-reg plugin

### PR DESCRIPTION
**Pull request by miheer**
A Dockerfile has been created where the image built from it can provide an environment for ANTs and pl-antsreg in the container. The container built with this image will have ANTs built in it along with the pl-antsreg.

Containerzing  ANTs ->
1) cloning ANTS with tag v2.2.0
2) Installing all build utilities
3) building ANTS 
4) Installing python.
5) cloning pl-antsreg
6) run pip
7) set entry point with antsreg.py

You will need to do the following steps->
docker build .
mkdir incoming
mkdir outgoing
chmod 777 incoming
chmod 777 outgoing

docker run -it -v $(pwd)/incoming:/incoming -v $(pwd)/outgoing:/outgoing  <image id>  /bin/bash antsreg.py  /incoming   /outgoing

### CODE REVIEW

**Comment by jbernal0019** [comment]
Hey @miheer 

It's great you are creating this ANTs env. But there are some things to consider for this to work with our platform:

First while our plugins' docker images are as free-form as possible they are not fully free-form. There is the following constraint. The command:

`docker run --rm fnndsc/pl-antsreg`

should by default return the same as:

`docker run --rm fnndsc/pl-antsreg antsreg.py --json`

That is, when running a CUBE's plugin container with no extra arguments it should return a JSON representation of the plugin. Note that this is assuming **Python3** as the **entrypoint**.

And second we want to reuse your effort for future plugins :)
So I'm proposing the following:

1. I'm going to create a repo called **centos-python3** so you can create there a Dockerfile for a Docker image with **Python3** and **pip** installed on **Centos**. It should work exactly as in this repo: 

https://github.com/FNNDSC/ubuntu-python3

2. All you need to do in this pl-antsreg repo is reusing the Dockerfile exactly as it is in **master** branch but just change `FROM fnndsc/ubuntu-python3:latest` to `FROM fnndsc/centos-python3:latest`. Of course you will also need to add the `RUN` command to install ANTs stuff.

Hoper this makes sense. Cheers.

**Comment by danmcp** [comment]
@jbernal0019 I don't think we need 2 repos as we are all working toward the same end goal.  Is there a rule that says all images must be ubuntu based?

**Comment by jbernal0019** [comment]
Hey @danmcp No,  there isn't any rule that says all images must be Ubuntu-based. They can be Centos-based too. You can certainly create a successful docker image here without the need of another repo but there are many reasons to bettr have two repos and base this image on the `fnndsc/centos-python3` image. 

1. We can reuse  `fnndsc/centos-python3` as the base for other Centos-based plugin images
2. We reduce the size and complexity of the Dockerfile for this and other Centos-based plugins. The Dockerfile for this plugin is actually already too big and complex than usual
3. We reduce network bandwidth usage by using a common image for all Centos-based plugins. As the the Union FS layers for the base image will already be downloaded for any Centos-based plugins
4. The more `RUN` and other Docker commands you use in a Dockerfile the bigger the resulting image as they add up as independent layers to the Union FS. Please try to reduce the number of `RUN` (and other commands) commands in a single Dockerfile.

More reasons I can't remember now ...   :)

**Comment by danmcp** [comment]
@jbernal0019 Sorry, I misread part of your original comment.  Since you closed this issue, I was thinking you wanted to make a separate antsreg repo as well for centos.  I agree it makes sense to have a separate centos parent image.

**Comment by Chris210634** [comment]
Hi @miheer @danmcp @jbernal0019 ,

The Python installation part was moved to the centos-python3 Dockerfile. I added a few lines to the antsreg.py. it takes a --command argument.

Here's an example of how to run it.

'''
 git clone https://github.com/stnava/alphANTs
cd alphANTs
chmod 777 data output
sudo docker run -v $(pwd)/data:/incoming -v $(pwd)/output:/outgoing   \
        fnndsc/pl-antsreg antsreg.py /incoming /outgoing --command \
        "antsRegistrationSyNQuick.sh -d 2 -f /incoming/r16slice.jpg \
        -m /incoming/r64slice.jpg -t r -o /outgoing/rigid"
'''

**Comment by jbernal0019** [comment]
Hey @Chris210634 This is good. Just one design consideration: The idea of a system like Chris is to hide CLI program complexity from end users in the front end. A clinical doctor wouldn't want to deal with a CLI program with many flags, etc... The --command option is very flexible and general but requires the user to have a great deal of knowledge about ANTs. So maybe it should be optional and just give the user more specific options that can guide him. The less options the better. Clinical and many research folks just want to push a button and have the work done :)

**Comment by Chris210634** [comment]
Hi @jbernal0019 

Thanks for the feedback, I had the same discussion with @danmcp and am working on expanding the parser.

**Pull request closed without merging**
